server:
  servlet:
    encoding:
      force-response: true

spring:
  profiles:
    include: oauth

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL

  h2:
    console:
      enabled: true

  session:
    store-type: jdbc

  main:
    web-application-type: none